//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace АСК_ЭПБ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTATION
    {
        public int DOCUMENTATIONID { get; set; }
        public int WORK_REQUESTID { get; set; }
        public string NAME_DOCUMENTATION { get; set; }
        public string URL_DOCUMENTATION { get; set; }
    
        public virtual WORK_REQUEST WORK_REQUEST { get; set; }
    }
}
