//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace АСК_ЭПБ
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EQUIPMENT()
        {
            this.WORK_REQUEST = new HashSet<WORK_REQUEST>();
        }
    
        public int EQUIPMENTID { get; set; }
        public string NAME_EQUIPMENT { get; set; }
        public string TECHNICAL_DOCUMENTATION { get; set; }
        public int EQUIPMENT_STATEID { get; set; }
        public int EQUIPMENT_ACTIVITYID { get; set; }
        public Nullable<System.DateTime> LAST_DATE_CHECKS { get; set; }
    
        public virtual EQUIPMENT_STATE EQUIPMENT_STATE { get; set; }
        public virtual EQUIPMENT_ACTIVITY EQUIPMENT_ACTIVITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORK_REQUEST> WORK_REQUEST { get; set; }
    }
}
