//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace АСК_ЭПБ
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRATION_REQUST
    {
        public int REQUSTID { get; set; }
        public string EMAIL_REQUST { get; set; }
        public string PASSWORD_REQUST { get; set; }
        public string FIRSTNAME_REQUST { get; set; }
        public string LASTNAME_REQUST { get; set; }
        public string MIDDLENAME_REQUST { get; set; }
        public List<Roles> Roles { get; set; }
        public string SelectedRole { get; set; }
    }
}
