//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace АСК_ЭПБ
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORK_REQUEST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WORK_REQUEST()
        {
            this.DOCUMENTATION = new HashSet<DOCUMENTATION>();
        }
    
        public int WORK_REQUESTID { get; set; }
        public int EQUIPMENTID { get; set; }
        public int WORK_TYPEID { get; set; }
        public int REQUEST_STATUSID { get; set; }
        public int CONTRACTORID { get; set; }
        public System.DateTime DATA_CREATION { get; set; }
        public string URL_WORK_REQUEST { get; set; }
    
        public virtual CONTRACTOR CONTRACTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENTATION> DOCUMENTATION { get; set; }
        public virtual EQUIPMENT EQUIPMENT { get; set; }
        public virtual REQUEST_STATUS REQUEST_STATUS { get; set; }
        public virtual WORK_TYPE WORK_TYPE { get; set; }
    }
}
